### ISSUE TITLE
Add a way to share the app

### ISSUE THREAD

**Issue by Dostoi** [Nutomic/ensichat#5]
Is it possible to add a way to share the app ?
The case where the app would be the most needed are those when we don't have a connection or a bad one (or at least for me ^^) so other people can't go on the internet and get the app.

**Comment by Nutomic** [comment]
You could use the [swap feature in F-Droid](https://f-droid.org/forums/topic/turn-your-device-into-an-app-store/) for this. Also, you could send it as a normal file over Bluetooth.

It doesn't really make sense to put this into ensichat, because the app needs to be installed on both devices to work.

**Comment by TameOfGroans** [comment]
@Dostoi Does your device not support wifi direct?

**Comment by Dostoi** [comment]
I was thinking about something more like what gilgamesh is doing, it's a link that let you select the way to share the app, you don't have to share it only with the app. As not everyone have F-droid, so if you share the app with them they can't do it with other and I didn't manage to find where the app was installed so I can't send it with bluetooth. 
But it's more to have a simple way to share it other than F-droid.

It should have it but I never manage to find the option about it

**Comment by Nutomic** [comment]
Ah just a normal "share" action that sends the apk. Good idea :+1:

**Comment by Dostoi** [comment]
I wasn't clear, my bad ^^
